import { useContext, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import { usercontext } from "../appcontext.jsx";
import { BrandNav, EmptyState, Footer } from "../ui.jsx";
import Styles from "./jobs.module.css";

function Applications() {
  const navigate = useNavigate();
  const { role, serviceURL, islogged, username } = useContext(usercontext);
  const [isloading, setisloading] = useState(true);
  const [items, setitems] = useState([]);
  const [loadError, setLoadError] = useState("");

  const normalizeApplication = (item, index) => {
    const job = item?.job || item?.jobPost || item?.recruiterJobPost || {};
    return {
      applicationId: item?.applicationId || item?.id || `${job.id || "application"}-${index}`,
      appliedAt: item?.appliedAt || null,
      job: {
        id: job.id || "",
        title: job.title || "Job removed",
        companyName: job.companyName || "Company N/A",
        location: job.location || "Location N/A",
        workMode: job.workMode || "Mode N/A",
        employmentType: job.employmentType || "Type N/A",
        experienceLevel: job.experienceLevel || "Experience N/A",
        salaryRange: job.salaryRange || "Salary N/A",
        skills: job.skills || "Not specified",
        description: job.description || "No description available.",
      },
    };
  };

  const loadApplications = () => {
    setisloading(true);
    setLoadError("");
    fetch(`${serviceURL}/jobs/applied`, { method: "get", credentials: "include" })
      .then((response) => {
        if (response.ok) return response.json();
        return response.text().then((t) => {
          throw new Error(t || "Failed to load applications");
        });
      })
      .then((data) => setitems(Array.isArray(data) ? data.map(normalizeApplication) : []))
      .catch((err) => {
        const message = err.message || "Network error";
        setLoadError(message);
        toast.error(message);
      })
      .finally(() => setisloading(false));
  };

  useEffect(() => {
    if (!islogged) {
      navigate("/login");
      return;
    }
    if (role !== "JOB_SEEKER") {
      navigate("/");
      return;
    }
    loadApplications();
  }, [islogged, role, navigate, serviceURL]);

  return (
    <div className={Styles.page}>
      <BrandNav active="My Applications" userInitial={username ? username[0].toUpperCase() : ""} />
      <main className={Styles.main}>
        <section className={Styles.header}>
          <div>
            <button className={Styles.textBack} onClick={() => navigate("/")}>Back</button>
            <h1>My Applications</h1>
            <p>Track where you've applied and monitor your recruitment progress.</p>
          </div>
          <div className={Styles.stats}>
            <div><span>Total Active</span><b>{items.length} Applications</b></div>
            <div><span>Job Records</span><b>{items.filter((item) => item.job?.id).length}</b></div>
          </div>
        </section>

        {isloading ? (
          <p className={Styles.count}>Loading applications...</p>
        ) : loadError ? (
          <EmptyState
            icon="!"
            title="Applications could not load"
            text={loadError}
            primary={<button className={Styles.bigPrimary} onClick={loadApplications}>Retry</button>}
            secondary={<button className={Styles.bigSecondary} onClick={() => navigate("/jobs")}>Browse Jobs</button>}
          />
        ) : items.length === 0 ? (
          <EmptyState
            icon="[]"
            title="You haven't applied to any jobs yet"
            text="Your career journey begins here. Explore tailored roadmaps and high-precision job matches generated by our AI co-pilot."
            primary={<button className={Styles.bigPrimary} onClick={() => navigate("/jobs")}>Explore Opportunities</button>}
            secondary={<button className={Styles.bigSecondary} onClick={() => navigate("/careerroadmap")}>View Recommended Roadmaps</button>}
          />
        ) : (
          <div className={Styles.jobGrid}>
            {items.map((it) => {
              const j = it.job || {};
              return (
                <article key={it.applicationId || `${it.appliedAt}-${j.id}`} className={Styles.featuredJob}>
                  <div className={Styles.thumb}></div>
                  <div className={Styles.jobBody}>
                    <div className={Styles.row}>
                      <h2>{j.title || "Job removed"}</h2>
                      <span>{it.appliedAt ? new Date(it.appliedAt).toLocaleDateString() : "Applied"}</span>
                    </div>
                    <p className={Styles.meta}>{j.companyName} - {j.location} - {j.workMode}</p>
                    <p>{j.description}</p>
                    <div className={Styles.tagRow}>
                      <span>{j.employmentType}</span>
                      <span>{j.experienceLevel}</span>
                      <span>{j.salaryRange}</span>
                      <span>Skills: {j.skills}</span>
                    </div>
                  </div>
                </article>
              );
            })}
          </div>
        )}

        <section className={Styles.resourceCards}>
          <button type="button" onClick={() => navigate("/jobs")}><h2>Market Insights</h2><p>See how your skills stack up against current industry demands.</p></button>
          <button type="button" onClick={() => navigate("/codingtest")}><h2>AI Interview Prep</h2><p>Practice with specialized recruitment AI to polish your performance.</p></button>
          <button type="button" onClick={() => navigate("/careerroadmap")}><h2>Career Roadmaps</h2><p>Personalized pathways designed to bridge your current gap to senior roles.</p></button>
        </section>
      </main>
      <Footer />
    </div>
  );
}

export default Applications;
